# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  carfyorcamento.api:
    build:
      context: "/Users/michaelfaleiro/Projetos/Carfy/CarfyOrcamento"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    entrypoint:
    - "/opt/rider-debugger/linux-musl-arm64/dotnet/dotnet"
    - "exec"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "/Users/michaelfaleiro/.local/share/JetBrains/RiderRemoteDebugger/2024.2.6/LinuxMuslArm64:/opt/rider-debugger"
    - "/Users/michaelfaleiro/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/michaelfaleiro/Library/Logs/JetBrains/Rider2024.2/DebuggerWorker/JetBrains.Debugger.Worker.2024_10_23_07_42_14:/var/opt/rider-debugger:rw"
