# This is a generated file. Not intended for manual editing.
services:
  carfyorcamento.api:
    build:
      context: "C:\\Projetos\\Carfy\\CarfyOrcamento\\src\\CarfyOrcamento.Api"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CarfyOrcamento.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "carfyorcamento.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\maico\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projetos\\Carfy\\CarfyOrcamento\\src\\CarfyOrcamento.Api:/app:rw"
    - "C:\\Projetos\\Carfy\\CarfyOrcamento:/src:rw"
    working_dir: "/app"
