version: '3.8'

services:
  carfyorcamento.api:
    container_name: carfyorcamento.api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
      
    ports:
      - "5002:5002"
      
    networks:
      - carfyorcamento-network
    depends_on:
      - postgres-carfy
  
  postgres-carfy:
    container_name: postgres-carfy
    image: "arm64v8/postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CarfyOrcamento
    
    ports:
        - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - carfyorcamento-network

networks:
  carfyorcamento-network:
    driver: bridge

volumes:
    postgres-data:
        driver: local